### ISSUE TITLE
TestChimeraFit2 fails

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-chimera#17]
both fails:
Run chimera from imported mmCIF file without imported or mmCIF-associated volume
Run Chimera from imported pdb file without imported or pdb-associated volume
```
>>> ERROR running protocol chimera fit
 no volume
 associated to pdb
    FAILED with error: Protocol has validation errors:
Error: You should provide a volume.
```

**Comment by rmarabini** [comment]
This is not an error. We check that  if no volume is provided the protocol fails.
