### ISSUE TITLE
Error importing symbol after update

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-chimera#5]
@rmarabini @mmmtnez After updating the plugin to the lastest version, I'm getting an import error: 

```
error when importing from chimera.protocols: cannot import name SYM_I2n3
   File "/home/josem/work/development/scipion-em-plugins/scipion-em-chimera/chimera/protocols/protocol_contacts.py", line 2, in <module>
```

**Comment by rmarabini** [comment]
@Jose Miguel de la Rosa Trevin <delarosatrevin@gmail.com>  @Marta Martinez
<mmmtnez@cnb.csic.es>,

  Hi,

      The values are defined in branch release-2.0.0-fixed but not -yet- in
release-2.0.0.
I just created a pull request to merge both branches. If somebody approves
it
This issue will be fixed.

**Comment by rmarabini** [comment]
I think this is solved after merge

**Comment by marta** [comment]
@rmarabini I think you meant to @ someone else

**Comment by delarosatrevin** [comment]
Yep, thanks @rmarabini ! I just look at the introduced changes and test were passing.
