### ISSUE TITLE
scipionchimera plugin when installation fails 

### ISSUE THREAD

**Issue by fonsecareyna82** [scipion-em/scipion-em-chimera#52]
If the scipionchimera plugin fails the installation, it is marked as installed

**Comment by rmarabini** [comment]
@fonsecareyna82 I have no idea how the plugin installation works. I do not think I can help here.

     Roberto

**Comment by rmarabini** [comment]
I have installed chimera plugin a  few times this month and the installation was OK. I close this issue but I do not know if this problem has been addressed.
