### ISSUE TITLE
example in tutorial to subtract volumes is wrong

### ISSUE THREAD

**Issue by mmmtnez** [scipion-em/scipion-em-chimera#7]
because no equalization of grey values is done. 

a) check if this step may be done properlly in chimera
b) even better implement protocol

**Comment by rmarabini** [comment]
New protocol to be impletented in protocol protocol_subtraction_maps.py

**Comment by rmarabini** [comment]
new protocol implemente. Have we updated the manual?

**Comment by rmarabini** [comment]
yes, it has been updated
