### ISSUE TITLE
import CIF with nucleotides fails in chimera

### ISSUE THREAD

**Issue by mmmtnez** [scipion-em/scipion-em-chimera#8]
Import preprocess CIFs
chimera fail to open this cif is there are nucleotides
Note: chimera is able to open original cifs
Note: other programs fail if no preprocessing is done
Note: phenix is able to read the preprocessed cif

**Comment by mmmtnez** [comment]
it seems that the important table in the cif file is 

loop_
_entity_poly_seq.entity_id 
_entity_poly_seq.num 
_entity_poly_seq.mon_id 
_entity_poly_seq.hetero 
1 1   ALA n 
1 2   ARG n 
1 3   THR n 

possible solution. 
scipion check:
1) file format is CIF
2) does the  label _entity_poly_seq.entity_id exist?
3 If it does then skip reading/writting with biopython 

======

how to search 

import mmap
def checklabelInFile(filename, label):
     f = open('filename')
     s = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)
     if s.find(label) != -1:
         return true
     else:
        return false

**Comment by rmarabini** [comment]
This is done
