### ISSUE TITLE
Update ChimeraX binaries to 1.6.1

### ISSUE THREAD

**Issue by MartinSalinas98** [scipion-em/scipion-em-chimera#98]
On the latest Ubuntu release (22.04), chimeraX 1.4 causes errors, since it requires `libffi.so.6`, which is no longer available by default in such OS version. However, chimeraX 1.6.1 (latest version as of the day of creating this issue), uses greater versions of the libffi shared object.

There are workarounds to make chimeraX 1.4 work in Ubuntu 22.04, but the better long-term solution is to update the binaries's version so it just works out of the box without needing any special hacks that would need to be made in each Ubuntu 22.04 machine.

**Comment by azazellochg** [comment]
done in https://github.com/scipion-em/scipion-em-chimera/pull/100
